import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar05Page from "@/components/navbar-05/navbar-05";
import Footer04Page from "@/components/footer-04/footer-04";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar05Page/>
        {children}
        <Footer04Page/>
      </body>
    </html>
  );
}
