# Generated by Django 5.1.4 on 2025-05-04 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Electronics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('mobile_phones', 'Mobile Phones'), ('laptops_tablets', 'Laptops & Tablets'), ('cameras', 'Cameras'), ('audio_devices', 'Audio Devices (Headphones, Speakers)'), ('smart_watches', 'Smart Watches'), ('wearable_tech', 'Wearable Tech'), ('accessories', 'Accessories (Chargers, Cases, etc.)')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electronics', models.ManyToManyField(blank=True, related_name='electronics', to='SearchFiltering.electronics')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size', models.CharField(blank=True, max_length=10, null=True)),
                ('color', models.CharField(blank=True, max_length=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='SearchFiltering.category')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_by', models.CharField(choices=[('newest', 'Newest'), ('oldest', 'Oldest'), ('highest-rating', 'Highest Rating'), ('lowest-rating', 'Lowest Rating'), ('most-helpful', 'Most Helpful')], default='newest', max_length=50)),
                ('rating', models.PositiveIntegerField()),
                ('comment', models.TextField()),
                ('helpful_votes', models.PositiveIntegerField(default=0)),
                ('reported', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='SearchFiltering.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='reating',
            field=models.ManyToManyField(blank=True, related_name='reating', to='SearchFiltering.review'),
        ),
    ]
