# Generated by Django 5.1.4 on 2025-05-04 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SearchFiltering', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='electronics',
        ),
        migrations.AddField(
            model_name='category',
            name='electronics',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='electronics', to='SearchFiltering.electronics'),
        ),
    ]
