# Generated by Django 5.1.4 on 2025-10-04 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SearchFiltering', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='review',
            name='helpful_votes',
        ),
        migrations.RemoveField(
            model_name='review',
            name='reported',
        ),
        migrations.RemoveField(
            model_name='review',
            name='sort_by',
        ),
    ]
