# Generated by Django 5.1.4 on 2025-05-08 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SearchFiltering', '0002_remove_category_electronics_category_electronics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('fiction', 'Fiction'), ('non_fiction', 'Non-Fiction'), ('children', 'Children'), ('young_adult', 'Young Adult'), ('education', 'Education'), ('science', 'Science'), ('history', 'History'), ('biography', 'Biography'), ('fantasy', 'Fantasy'), ('romance', 'Romance'), ('mystery', 'Mystery & Thriller'), ('comics', 'Comics & Graphic Novels'), ('self_help', 'Self Help'), ('technology', 'Technology'), ('religion', 'Religion & Spirituality'), ('business', 'Business & Economics')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('tshirt', 'T-Shirt'), ('shirt', 'Shirt'), ('hoodie', 'Hoodie'), ('jacket', 'Jacket'), ('jeans', 'Jeans'), ('shorts', 'Shorts'), ('trousers', 'Trousers'), ('sweater', 'Sweater'), ('school_uniform', 'School Uniform'), ('sportswear', 'Sportswear'), ('nightwear', 'Nightwear'), ('ethnic_wear', 'Ethnic Wear'), ('casual_wear', 'Casual Wear'), ('formal_wear', 'Formal Wear')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='HOMEGARDEN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('furniture', 'Furniture'), ('bedding', 'Bedding & Linens'), ('kitchen', 'Kitchen & Dining'), ('appliances', 'Home Appliances'), ('decor', 'Home Decor'), ('lighting', 'Lighting'), ('garden_tools', 'Garden Tools'), ('plants', 'Plants & Seeds'), ('storage', 'Storage & Organization'), ('cleaning', 'Cleaning Supplies'), ('bathroom', 'Bathroom Accessories'), ('outdoor', 'Outdoor Furniture & Equipment'), ('tools', 'Hand & Power Tools')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SportOutdoors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('fitness_equipment', 'Fitness Equipment'), ('sportswear', 'Sportswear'), ('footwear', 'Sports Footwear'), ('camping_hiking', 'Camping & Hiking'), ('cycling', 'Cycling'), ('swimming', 'Swimming Gear'), ('team_sports', 'Team Sports (Football, Cricket, etc.)'), ('outdoor_games', 'Outdoor Games'), ('sports_accessories', 'Sports Accessories'), ('yoga', 'Yoga & Meditation'), ('water_sports', 'Water Sports'), ('fishing', 'Fishing Equipment'), ('winter_sports', 'Winter Sports Gear')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='clothings',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clothing', to='SearchFiltering.clothing'),
        ),
    ]
