# Generated by Django 5.1.4 on 2025-05-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SearchFiltering', '0003_book_clothing_homegarden_sportoutdoors_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.RemoveField(
            model_name='category',
            name='clothings',
        ),
        migrations.RemoveField(
            model_name='category',
            name='electronics',
        ),
        migrations.DeleteModel(
            name='HOMEGARDEN',
        ),
        migrations.DeleteModel(
            name='SportOutdoors',
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('ALL', 'All Categories'), ('CLOTHES', 'Clothes and Wear'), ('HOME', 'Home Interiors'), ('ELECTRONICS', 'Electronics'), ('BEAUTY', 'Beauty & Health'), ('SPORTS', 'Sports & Outdoors')], default='ALL', max_length=100),
        ),
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Clothing',
        ),
        migrations.DeleteModel(
            name='Electronics',
        ),
    ]
