# Generated by Django 5.1.4 on 2025-05-10 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SearchFiltering', '0004_delete_book_remove_category_clothings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='reating',
        ),
    ]
